#!/bin/sh

# test the array solver

PRI=../../princess

TESTS="downwardsPropagation.smt2 \
       downwardsPropagation2.smt2 \
       constPropagation.smt2 \
       arrays.smt2 arrays2.smt2 arrays3.smt2 \
       arrays4.smt2 arrays5.smt2 arrays6.smt2 \
       boolean-array.smt2 array-sorted.smt2 array-sorted-2.smt2 \
       extensionality1.smt2 extensionality2.smt2 extensionality3.smt2 \
       extensionality4.smt2 extensionality4b.smt2 extensionality5.smt2 \
       extensionality6.smt2 quantifiers.smt2 lambda.smt2 lambda2.smt2 \
       lambda3.smt2"

$PRI "$@" $TESTS

$PRI "$@" decoding.smt2

