/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensmt;

public class PTRef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PTRef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PTRef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmtNativeJNI.delete_PTRef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(long value) {
    OsmtNativeJNI.PTRef_x_set(swigCPtr, this, value);
  }

  public long getX() {
    return OsmtNativeJNI.PTRef_x_get(swigCPtr, this);
  }

  public static PTRef getUndef() {
    long cPtr = OsmtNativeJNI.PTRef_Undef_get();
    return (cPtr == 0) ? null : new PTRef(cPtr, false);
  }

  public PTRef() {
    this(OsmtNativeJNI.new_PTRef(), true);
  }

}
