/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensmt;

public class SMTConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SMTConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SMTConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SMTConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmtNativeJNI.delete_SMTConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SMTConfig() {
    this(OsmtNativeJNI.new_SMTConfig(), true);
  }

  public void setBooleanInterpolationAlgorithm(ItpAlgorithm i) {
    OsmtNativeJNI.SMTConfig_setBooleanInterpolationAlgorithm(swigCPtr, this, ItpAlgorithm.getCPtr(i), i);
  }

  public void setEUFInterpolationAlgorithm(ItpAlgorithm i) {
    OsmtNativeJNI.SMTConfig_setEUFInterpolationAlgorithm(swigCPtr, this, ItpAlgorithm.getCPtr(i), i);
  }

  public void setLRAInterpolationAlgorithm(ItpAlgorithm i) {
    OsmtNativeJNI.SMTConfig_setLRAInterpolationAlgorithm(swigCPtr, this, ItpAlgorithm.getCPtr(i), i);
  }

  public void setLRAStrengthFactor(String factor) {
    OsmtNativeJNI.SMTConfig_setLRAStrengthFactor(swigCPtr, this, factor);
  }

}
