/*
 *  JavaSMT is an API wrapper for a collection of SMT solvers.
 *  This file is part of JavaSMT.
 *
 *  Copyright (C) 2007-2016  Dirk Beyer
 *  All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.sosy_lab.java_smt.solvers.dreal4.drealjni;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public class Context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Context obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize1() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DrealJNI.deleteContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Context() {
    this(DrealJNI.newContextSWIG0(), true);
  }

  public Context(Context context) {
    this(DrealJNI.newContextSWIG1(Context.swigRelease(context), context), true);
  }

  public Context(Config config) {
    this(DrealJNI.newContextSWIG2(Config.getCPtr(config), config), true);
  }

  public void assertion(Formula f) {
    DrealJNI.contextAssert(swigCPtr, this, Formula.getCPtr(f), f);
  }

  public SwigTypePOptionalTDrealBoxT checkSat() {
    return new SwigTypePOptionalTDrealBoxT(DrealJNI.contextCheckSat(swigCPtr, this), true);
  }

  public void declareVariable(Variable v, boolean is_model_variable) {
    DrealJNI.contextDeclareVariableSWIG0(
        swigCPtr, this, Variable.getCPtr(v), v, is_model_variable);
  }

  public void declareVariable(Variable v) {
    DrealJNI.contextDeclareVariableSWIG1(swigCPtr, this, Variable.getCPtr(v), v);
  }

  public void declareVariable(Variable v, Expression lb, Expression ub, boolean is_model_variable) {
    DrealJNI.contextDeclareVariableSWIG2(
        swigCPtr,
        this,
        Variable.getCPtr(v),
        v,
        Expression.getCPtr(lb),
        lb,
        Expression.getCPtr(ub),
        ub,
        is_model_variable);
  }

  public void declareVariable(Variable v, Expression lb, Expression ub) {
    DrealJNI.contextDeclareVariableSWIG3(
        swigCPtr,
        this,
        Variable.getCPtr(v),
        v,
        Expression.getCPtr(lb),
        lb,
        Expression.getCPtr(ub),
        ub);
  }

  public static void exit() {
    DrealJNI.contextExit();
  }

  public void minimize(Expression f) {
    DrealJNI.contextMinimizeSWIG0(swigCPtr, this, Expression.getCPtr(f), f);
  }

  public void minimize(ExpressionVector functions) {
    DrealJNI.contextMinimizeSWIG1(
        swigCPtr, this, ExpressionVector.getCPtr(functions), functions);
  }

  public void maximize(Expression f) {
    DrealJNI.contextMaximize(swigCPtr, this, Expression.getCPtr(f), f);
  }

  public void pop(int n) {
    DrealJNI.contextPop(swigCPtr, this, n);
  }

  public void push(int n) {
    DrealJNI.contextPush(swigCPtr, this, n);
  }

  public void setInfo(String key, double val) {
    DrealJNI.contextSetInfoSWIG0(swigCPtr, this, key, val);
  }

  public void setInfo(String key, String val) {
    DrealJNI.contextSetInfoSWIG1(swigCPtr, this, key, val);
  }

  public void setInterval(Variable v, double lb, double ub) {
    DrealJNI.contextSetInterval(swigCPtr, this, Variable.getCPtr(v), v, lb, ub);
  }

  public void setLogic(Logic logic) {
    DrealJNI.contextSetLogic(swigCPtr, this, logic.swigValue());
  }

  public void setOption(String key, double val) {
    DrealJNI.contextSetOptionSWIG0(swigCPtr, this, key, val);
  }

  public void setOption(String key, String val) {
    DrealJNI.contextSetOptionSWIG1(swigCPtr, this, key, val);
  }

  public SwigTypePOptionalTStdStringT getOption(String key) {
    return new SwigTypePOptionalTStdStringT(
        DrealJNI.contextGetOption(swigCPtr, this, key), true);
  }

  public Config config() {
    return new Config(DrealJNI.contextConfig(swigCPtr, this), false);
  }

  public Config mutableConfig() {
    return new Config(DrealJNI.contextMutableConfig(swigCPtr, this), false);
  }

  public static String version() {
    return DrealJNI.contextVersion();
  }

  public SwigTypePScopedVectorTDrealDrakeSymbolicFormulaT assertions() {
    return new SwigTypePScopedVectorTDrealDrakeSymbolicFormulaT(
        DrealJNI.contextAssertions(swigCPtr, this), false);
  }

  public Box box() {
    return new Box(DrealJNI.contextBox(swigCPtr, this), false);
  }

  public Box get_model() {
    return new Box(DrealJNI.contextGetModel(swigCPtr, this), false);
  }

  // self written
  public boolean checkSat(Box box) {
    return DrealJNI.contextCheckSat0(Context.getCPtr(this), Box.getCPtr(box));
  }

  public void declareVariables(Formula f) {
    DrealJNI.contextDeclareVariables(Context.getCPtr(this), Formula.getCPtr(f));
  }
}
