/*
 *  JavaSMT is an API wrapper for a collection of SMT solvers.
 *  This file is part of JavaSMT.
 *
 *  Copyright (C) 2007-2016  Dirk Beyer
 *  All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.sosy_lab.java_smt.solvers.dreal4.drealjni;


public class ExpressionExpressionMap extends java.util.AbstractMap<Expression, Expression> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExpressionExpressionMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExpressionExpressionMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ExpressionExpressionMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        drealJNI.delete_ExpressionExpressionMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof Expression)) {
      return false;
    }

    return containsImpl((Expression)key);
  }

  public Expression get(java.lang.Object key) {
    if (!(key instanceof Expression)) {
      return null;
    }

    Iterator itr = find((Expression) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public Expression put(Expression key, Expression value) {
    Iterator itr = find((Expression) key);
    if (itr.isNot(end())) {
      Expression oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public Expression remove(java.lang.Object key) {
    if (!(key instanceof Expression)) {
      return null;
    }

    Iterator itr = find((Expression) key);
    if (itr.isNot(end())) {
      Expression oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<Expression, Expression>> entrySet() {
    java.util.Set<Entry<Expression, Expression>> setToReturn =
        new java.util.HashSet<Entry<Expression, Expression>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<Expression, Expression>() {
        private Iterator iterator;

        private Entry<Expression, Expression> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public Expression getKey() {
          return iterator.getKey();
        }

        public Expression getValue() {
          return iterator.getValue();
        }

        public Expression setValue(Expression newValue) {
          Expression oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public ExpressionExpressionMap() {
    this(drealJNI.new_ExpressionExpressionMap__SWIG_0(), true);
  }

  public ExpressionExpressionMap(ExpressionExpressionMap other) {
    this(drealJNI.new_ExpressionExpressionMap__SWIG_1(ExpressionExpressionMap.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          drealJNI.delete_ExpressionExpressionMap_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private ExpressionExpressionMap.Iterator getNextUnchecked() {
      return new ExpressionExpressionMap.Iterator(drealJNI.ExpressionExpressionMap_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(ExpressionExpressionMap.Iterator other) {
      return drealJNI.ExpressionExpressionMap_Iterator_isNot(swigCPtr, this, ExpressionExpressionMap.Iterator.getCPtr(other), other);
    }
  
    private Expression getKey() {
      return new Expression(drealJNI.ExpressionExpressionMap_Iterator_getKey(swigCPtr, this), true);
    }
  
    private Expression getValue() {
      return new Expression(drealJNI.ExpressionExpressionMap_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(Expression newValue) {
      drealJNI.ExpressionExpressionMap_Iterator_setValue(swigCPtr, this, Expression.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return drealJNI.ExpressionExpressionMap_isEmpty(swigCPtr, this);
  }

  public void clear() {
    drealJNI.ExpressionExpressionMap_clear(swigCPtr, this);
  }

  private ExpressionExpressionMap.Iterator find(Expression key) {
    return new ExpressionExpressionMap.Iterator(drealJNI.ExpressionExpressionMap_find(swigCPtr, this, Expression.getCPtr(key), key), true);
  }

  private ExpressionExpressionMap.Iterator begin() {
    return new ExpressionExpressionMap.Iterator(drealJNI.ExpressionExpressionMap_begin(swigCPtr, this), true);
  }

  private ExpressionExpressionMap.Iterator end() {
    return new ExpressionExpressionMap.Iterator(drealJNI.ExpressionExpressionMap_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return drealJNI.ExpressionExpressionMap_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(Expression key) {
    return drealJNI.ExpressionExpressionMap_containsImpl(swigCPtr, this, Expression.getCPtr(key), key);
  }

  private void putUnchecked(Expression key, Expression value) {
    drealJNI.ExpressionExpressionMap_putUnchecked(swigCPtr, this, Expression.getCPtr(key), key, Expression.getCPtr(value), value);
  }

  private void removeUnchecked(ExpressionExpressionMap.Iterator itr) {
    drealJNI.ExpressionExpressionMap_removeUnchecked(swigCPtr, this, ExpressionExpressionMap.Iterator.getCPtr(itr), itr);
  }

}
