// This file is part of JavaSMT,
// an API wrapper for a collection of SMT solvers:
// https://github.com/sosy-lab/java-smt
//
// SPDX-FileCopyrightText: 2023 Dirk Beyer <https://www.sosy-lab.org>
//
// SPDX-License-Identifier: Apache-2.0

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.sosy_lab.java_smt.solvers.dreal4.drealjni;

import com.google.errorprone.annotations.CanIgnoreReturnValue;
import javax.annotation.concurrent.NotThreadSafe;

@NotThreadSafe
public class FormulaSet extends java.util.AbstractSet<Formula> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FormulaSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FormulaSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FormulaSet obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn) {
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      }
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize1() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DrealJNI.deleteFormulaSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FormulaSet(java.util.Collection<? extends Formula> collection) {
    this();
    addAll(collection);
  }

  @Override
  public int size() {
    return sizeImpl();
  }

  @Override
  public boolean add(Formula key) {
    return addImpl(key);
  }

  @CanIgnoreReturnValue
  @Override
  public boolean addAll(java.util.Collection<? extends Formula> collection) {
    boolean didAddElement = false;
    for (java.lang.Object object : collection) {
      didAddElement = add((Formula) object);
    }

    return didAddElement;
  }

  @Override
  public java.util.Iterator<Formula> iterator() {
    return new java.util.Iterator<Formula>() {
      private Iterator curr;
      private Iterator end;

      private java.util.Iterator<Formula> init() {
        curr = FormulaSet.this.begin();
        end = FormulaSet.this.end();
        return this;
      }

      @Override
      public Formula next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }

        // Save the current position, increment it,
        // then return the value at the position before the increment.
        final Formula currValue = curr.derefUnchecked();
        curr.incrementUnchecked();
        return currValue;
      }

      @Override
      public boolean hasNext() {
        return curr.isNot(end);
      }

      @Override
      public void remove() {
        throw new java.lang.UnsupportedOperationException();
      }
    }.init();
  }

  @Override
  public boolean containsAll(java.util.Collection<?> collection) {
    for (java.lang.Object object : collection) {
      if (!contains(object)) {
        return false;
      }
    }

    return true;
  }

  @Override
  public boolean contains(java.lang.Object object) {
    if (!(object instanceof Formula)) {
      return false;
    }

    return containsImpl((Formula) object);
  }

  @Override
  public boolean removeAll(java.util.Collection<?> collection) {
    boolean didRemoveElement = false;
    for (java.lang.Object object : collection) {
      didRemoveElement = remove(object);
    }

    return didRemoveElement;
  }

  @Override
  public boolean remove(java.lang.Object object) {
    if (!(object instanceof Formula)) {
      return false;
    }

    return removeImpl((Formula) object);
  }

  @NotThreadSafe
  protected static class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }

    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn) {
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        }
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize1() {
      delete();
    }

    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DrealJNI.deleteFormulaSetIterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }

    private void incrementUnchecked() {
      DrealJNI.formulaSetIteratorIncrementUnchecked(swigCPtr, this);
    }

    private Formula derefUnchecked() {
      return new Formula(DrealJNI.formulaSetIteratorDerefUnchecked(swigCPtr, this), true);
    }

    private boolean isNot(FormulaSet.Iterator other) {
      return DrealJNI.formulaSetIteratorIsNot(
          swigCPtr, this, FormulaSet.Iterator.getCPtr(other), other);
    }
  }

  public FormulaSet() {
    this(DrealJNI.newFormulaSetSWIG0(), true);
  }

  public FormulaSet(FormulaSet other) {
    this(DrealJNI.newFormulaSetSWIG1(FormulaSet.getCPtr(other), other), true);
  }

  @Override
  public boolean isEmpty() {
    return DrealJNI.formulaSetIsEmpty(swigCPtr, this);
  }

  @Override
  public void clear() {
    DrealJNI.formulaSetClear(swigCPtr, this);
  }

  private FormulaSet.Iterator begin() {
    return new FormulaSet.Iterator(DrealJNI.formulaSetBegin(swigCPtr, this), true);
  }

  private FormulaSet.Iterator end() {
    return new FormulaSet.Iterator(DrealJNI.formulaSetEnd(swigCPtr, this), true);
  }

  public boolean addImpl(Formula key) {
    return DrealJNI.formulaSetAddImpl(swigCPtr, this, Formula.getCPtr(key), key);
  }

  private boolean containsImpl(Formula key) {
    return DrealJNI.formulaSetContainsImpl(swigCPtr, this, Formula.getCPtr(key), key);
  }

  private boolean removeImpl(Formula key) {
    return DrealJNI.formulaSetRemoveImpl(swigCPtr, this, Formula.getCPtr(key), key);
  }

  private int sizeImpl() {
    return DrealJNI.formulaSetSizeImpl(swigCPtr, this);
  }

  @SuppressWarnings("unused")
  private boolean hasNextImpl(FormulaSet.Iterator itr) {
    return DrealJNI.formulaSetHasNextImpl(swigCPtr, this, FormulaSet.Iterator.getCPtr(itr), itr);
  }
}
