/*
 *  JavaSMT is an API wrapper for a collection of SMT solvers.
 *  This file is part of JavaSMT.
 *
 *  Copyright (C) 2007-2016  Dirk Beyer
 *  All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.sosy_lab.java_smt.solvers.dreal4.drealjni;

public class FormulaVector extends java.util.AbstractList<Formula>
    implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FormulaVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FormulaVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FormulaVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize1() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        drealJNI.delete_FormulaVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("unused")
  public FormulaVector(Formula[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Formula element : initialElements) {
      add(element);
    }
  }

  @SuppressWarnings("unused")
  public FormulaVector(Iterable<Formula> initialElements) {
    this();
    for (Formula element : initialElements) {
      add(element);
    }
  }

  @Override
  public Formula get(int index) {
    return doGet(index);
  }

  @Override
  public Formula set(int index, Formula e) {
    return doSet(index, e);
  }

  @Override
  public boolean add(Formula e) {
    modCount++;
    doAdd(e);
    return true;
  }

  @Override
  public void add(int index, Formula e) {
    modCount++;
    doAdd(index, e);
  }

  @Override
  public Formula remove(int index) {
    modCount++;
    return doRemove(index);
  }

  @Override
  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  @Override
  public int size() {
    return doSize();
  }

  public FormulaVector() {
    this(drealJNI.new_FormulaVector__SWIG_0(), true);
  }

  public FormulaVector(FormulaVector other) {
    this(drealJNI.new_FormulaVector__SWIG_1(FormulaVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return drealJNI.FormulaVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    drealJNI.FormulaVector_reserve(swigCPtr, this, n);
  }

  @Override
  public boolean isEmpty() {
    return drealJNI.FormulaVector_isEmpty(swigCPtr, this);
  }

  @Override
  public void clear() {
    drealJNI.FormulaVector_clear(swigCPtr, this);
  }

  public FormulaVector(int count, Formula value) {
    this(drealJNI.new_FormulaVector__SWIG_2(count, Formula.getCPtr(value), value), true);
  }

  private int doSize() {
    return drealJNI.FormulaVector_doSize(swigCPtr, this);
  }

  private void doAdd(Formula x) {
    drealJNI.FormulaVector_doAdd__SWIG_0(swigCPtr, this, Formula.getCPtr(x), x);
  }

  private void doAdd(int index, Formula x) {
    drealJNI.FormulaVector_doAdd__SWIG_1(swigCPtr, this, index, Formula.getCPtr(x), x);
  }

  private Formula doRemove(int index) {
    return new Formula(drealJNI.FormulaVector_doRemove(swigCPtr, this, index), true);
  }

  private Formula doGet(int index) {
    return new Formula(drealJNI.FormulaVector_doGet(swigCPtr, this, index), false);
  }

  private Formula doSet(int index, Formula val) {
    return new Formula(
        drealJNI.FormulaVector_doSet(swigCPtr, this, index, Formula.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    drealJNI.FormulaVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }
}
