/*
 *  JavaSMT is an API wrapper for a collection of SMT solvers.
 *  This file is part of JavaSMT.
 *
 *  Copyright (C) 2007-2016  Dirk Beyer
 *  All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.sosy_lab.java_smt.solvers.dreal4.drealjni;

public class Formula {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Formula(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Formula obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Formula obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize1() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        drealJNI.delete_Formula(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Formula() {
    this(drealJNI.new_Formula__SWIG_0(), true);
  }

  public Formula(Formula arg0) {
    this(drealJNI.new_Formula__SWIG_1(Formula.getCPtr(arg0), arg0), true);
  }

  public Formula AssignOperator(Formula arg0) {
    return new Formula(
        drealJNI.Formula_AssignOperator__SWIG_0(swigCPtr, this, Formula.getCPtr(arg0), arg0),
        false);
  }

  public Formula(Variable var) {
    this(drealJNI.new_Formula__SWIG_2(Variable.getCPtr(var), var), true);
  }

  public FormulaKind get_kind() {
    return FormulaKind.swigToEnum(drealJNI.Formula_get_kind(swigCPtr, this));
  }

  public long get_hash() {
    return drealJNI.Formula_get_hash(swigCPtr, this);
  }

  public Variables GetFreeVariables() {
    return new Variables(drealJNI.Formula_GetFreeVariables(swigCPtr, this), false);
  }

  public boolean EqualTo(Formula f) {
    return drealJNI.Formula_EqualTo(swigCPtr, this, Formula.getCPtr(f), f);
  }

  public boolean Less(Formula f) {
    return drealJNI.Formula_Less(swigCPtr, this, Formula.getCPtr(f), f);
  }

  public boolean Evaluate(Environment env) {
    return drealJNI.Formula_Evaluate__SWIG_0(swigCPtr, this, Environment.getCPtr(env), env);
  }

  public boolean Evaluate() {
    return drealJNI.Formula_Evaluate__SWIG_1(swigCPtr, this);
  }

  public Formula Substitute(Variable var, Expression e) {
    return new Formula(
        drealJNI.Formula_Substitute__SWIG_0(
            swigCPtr, this, Variable.getCPtr(var), var, Expression.getCPtr(e), e),
        true);
  }

  public Formula Substitute(Variable var, Formula f) {
    return new Formula(
        drealJNI.Formula_Substitute__SWIG_1(
            swigCPtr, this, Variable.getCPtr(var), var, Formula.getCPtr(f), f),
        true);
  }

  public Formula Substitute(
      SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Expression_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
          expr_subst,
      SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Formula_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
          formula_subst) {
    return new Formula(
        drealJNI.Formula_Substitute__SWIG_2(
            swigCPtr,
            this,
            SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Expression_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
                .getCPtr(expr_subst),
            SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Formula_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
                .getCPtr(formula_subst)),
        true);
  }

  public Formula Substitute(
      SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Expression_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
          expr_subst) {
    return new Formula(
        drealJNI.Formula_Substitute__SWIG_3(
            swigCPtr,
            this,
            SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Expression_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
                .getCPtr(expr_subst)),
        true);
  }

  public Formula Substitute(
      SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Formula_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
          formula_subst) {
    return new Formula(
        drealJNI.Formula_Substitute__SWIG_4(
            swigCPtr,
            this,
            SWIGTYPE_p_std__unordered_mapT_dreal__drake__symbolic__Variable_dreal__drake__symbolic__Formula_dreal__drake__hash_valueT_dreal__drake__symbolic__Variable_t_t
                .getCPtr(formula_subst)),
        true);
  }

  public String to_string() {
    return drealJNI.Formula_to_string(swigCPtr, this);
  }

  public static Formula True() {
    return new Formula(drealJNI.Formula_True(), true);
  }

  public static Formula False() {
    return new Formula(drealJNI.Formula_False(), true);
  }

  public boolean BoolOperator() {
    return drealJNI.Formula_BoolOperator(swigCPtr, this);
  }

  public static Formula make_conjunction(Formula f1, Formula f2) {
    return new Formula(
        drealJNI.Formula_make_conjunction(Formula.getCPtr(f1), f1, Formula.getCPtr(f2), f2), true);
  }

  public static Formula make_disjunction(Formula f1, Formula f2) {
    return new Formula(
        drealJNI.Formula_make_disjunction(Formula.getCPtr(f1), f1, Formula.getCPtr(f2), f2), true);
  }

  public boolean include_ite() {
    return drealJNI.Formula_include_ite(swigCPtr, this);
  }

  // self written
  public VariableSet getQuantifiedVariables() {
    VariableSet set = new VariableSet();
    drealJNI.Formula_getQuantifiedVariables(VariableSet.getCPtr(set), Formula.getCPtr(this));
    return set;
  }

  public VariableSet getFreeVariables() {
    VariableSet set = new VariableSet();
    drealJNI.Formula_getFreeVariables(VariableSet.getCPtr(set), Formula.getCPtr(this));
    return set;
  }
}
