// This file is part of JavaSMT,
// an API wrapper for a collection of SMT solvers:
// https://github.com/sosy-lab/java-smt
//
// SPDX-FileCopyrightText: 2023 Dirk Beyer <https://www.sosy-lab.org>
//
// SPDX-License-Identifier: Apache-2.0

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.sosy_lab.java_smt.solvers.dreal4.drealjni;

import javax.annotation.concurrent.NotThreadSafe;

@NotThreadSafe
public class VariableIntUnorderedMap extends java.util.AbstractMap<Variable, Integer> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VariableIntUnorderedMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VariableIntUnorderedMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VariableIntUnorderedMap obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn) {
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      }
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize1() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DrealJNI.deleteVaribaleIntUnorderedMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public int size() {
    return sizeImpl();
  }

  @Override
  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof Variable)) {
      return false;
    }

    return containsImpl((Variable) key);
  }

  @Override
  public Integer get(java.lang.Object key) {
    if (!(key instanceof Variable)) {
      return null;
    }

    Iterator itr = find((Variable) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  @Override
  public Integer put(Variable key, Integer value) {
    Iterator itr = find(key);
    if (itr.isNot(end())) {
      Integer oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  @Override
  public Integer remove(java.lang.Object key) {
    if (!(key instanceof Variable)) {
      return null;
    }

    Iterator itr = find((Variable) key);
    if (itr.isNot(end())) {
      Integer oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  @Override
  public java.util.Set<Entry<Variable, Integer>> entrySet() {
    java.util.Set<Entry<Variable, Integer>> setToReturn = new java.util.HashSet<>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(
          new Entry<Variable, Integer>() {
            private Iterator iterator;

            private Entry<Variable, Integer> init(Iterator iter) {
              this.iterator = iter;
              return this;
            }

            @Override
            public Variable getKey() {
              return iterator.getKey();
            }

            @Override
            public Integer getValue() {
              return iterator.getValue();
            }

            @Override
            public Integer setValue(Integer newValue) {
              Integer oldValue = iterator.getValue();
              iterator.setValue(newValue);
              return oldValue;
            }
          }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public VariableIntUnorderedMap() {
    this(DrealJNI.newVaribaleIntUnorderedMapSWIG0(), true);
  }

  public VariableIntUnorderedMap(VariableIntUnorderedMap other) {
    this(
        DrealJNI.newVaribaleIntUnorderedMapSWIG1(VariableIntUnorderedMap.getCPtr(other), other),
        true);
  }

  @NotThreadSafe
  protected static class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }

    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn) {
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        }
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize1() {
      delete();
    }

    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DrealJNI.deleteVaribaleIntUnorderedMapIterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }

    private VariableIntUnorderedMap.Iterator getNextUnchecked() {
      return new VariableIntUnorderedMap.Iterator(
          DrealJNI.varibaleIntUnorderedMapIteratorGetNextUnchecked(swigCPtr, this), true);
    }

    private boolean isNot(VariableIntUnorderedMap.Iterator other) {
      return DrealJNI.varibaleIntUnorderedMapIteratorIsNot(
          swigCPtr, this, VariableIntUnorderedMap.Iterator.getCPtr(other), other);
    }

    private Variable getKey() {
      return new Variable(DrealJNI.varibaleIntUnorderedMapIteratorGetKey(swigCPtr, this), true);
    }

    private int getValue() {
      return DrealJNI.varibaleIntUnorderedMapIteratorGetValue(swigCPtr, this);
    }

    private void setValue(int newValue) {
      DrealJNI.varibaleIntUnorderedMapIteratorSetValue(swigCPtr, this, newValue);
    }
  }

  @Override
  public boolean isEmpty() {
    return DrealJNI.varibaleIntUnorderedMapIsEmpty(swigCPtr, this);
  }

  @Override
  public void clear() {
    DrealJNI.varibaleIntUnorderedMapClear(swigCPtr, this);
  }

  private VariableIntUnorderedMap.Iterator find(Variable key) {
    return new VariableIntUnorderedMap.Iterator(
        DrealJNI.varibaleIntUnorderedMapFind(swigCPtr, this, Variable.getCPtr(key), key), true);
  }

  private VariableIntUnorderedMap.Iterator begin() {
    return new VariableIntUnorderedMap.Iterator(
        DrealJNI.varibaleIntUnorderedMapBegin(swigCPtr, this), true);
  }

  private VariableIntUnorderedMap.Iterator end() {
    return new VariableIntUnorderedMap.Iterator(
        DrealJNI.varibaleIntUnorderedMapEnd(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return DrealJNI.varibaleIntUnorderedMapSizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(Variable key) {
    return DrealJNI.varibaleIntUnorderedMapContainsImpl(swigCPtr, this, Variable.getCPtr(key), key);
  }

  private void putUnchecked(Variable key, int value) {
    DrealJNI.varibaleIntUnorderedMapPutUnchecked(swigCPtr, this, Variable.getCPtr(key), key, value);
  }

  private void removeUnchecked(VariableIntUnorderedMap.Iterator itr) {
    DrealJNI.varibaleIntUnorderedMapRemoveUnchecked(
        swigCPtr, this, VariableIntUnorderedMap.Iterator.getCPtr(itr), itr);
  }
}
