/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sosy_lab.java_smt.solvers.dreal4.drealjni;

public class VariableSet extends java.util.AbstractSet<Variable> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VariableSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VariableSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VariableSet obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize1() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        drealJNI.delete_VariableSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VariableSet(java.util.Collection<? extends Variable> collection) {
    this();
    addAll(collection);
  }

  @Override
  public int size() {
    return sizeImpl();
  }

  @Override
  public boolean add(Variable key) {
    return addImpl(key);
  }

  @Override
  public boolean addAll(java.util.Collection<? extends Variable> collection) {
    boolean didAddElement = false;
    for (java.lang.Object object : collection) {
      didAddElement |= add((Variable) object);
    }

    return didAddElement;
  }

  @Override
  public java.util.Iterator<Variable> iterator() {
    return new java.util.Iterator<Variable>() {
      private Iterator curr;
      private Iterator end;

      private java.util.Iterator<Variable> init() {
        curr = VariableSet.this.begin();
        end = VariableSet.this.end();
        return this;
      }

      @Override
      public Variable next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }

        // Save the current position, increment it,
        // then return the value at the position before the increment.
        final Variable currValue = curr.derefUnchecked();
        curr.incrementUnchecked();
        return currValue;
      }

      @Override
      public boolean hasNext() {
        return curr.isNot(end);
      }

      @Override
      public void remove() {
        throw new java.lang.UnsupportedOperationException();
      }
    }.init();
  }

  @Override
  public boolean containsAll(java.util.Collection<?> collection) {
    for (java.lang.Object object : collection) {
      if (!contains(object)) {
        return false;
      }
    }

    return true;
  }

  @Override
  public boolean contains(java.lang.Object object) {
    if (!(object instanceof Variable)) {
      return false;
    }

    return containsImpl((Variable) object);
  }

  @Override
  public boolean removeAll(java.util.Collection<?> collection) {
    boolean didRemoveElement = false;
    for (java.lang.Object object : collection) {
      didRemoveElement |= remove(object);
    }

    return didRemoveElement;
  }

  @Override
  public boolean remove(java.lang.Object object) {
    if (!(object instanceof Variable)) {
      return false;
    }

    return removeImpl((Variable) object);
  }

  protected static class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }

    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize1() {
      delete();
    }

    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          drealJNI.delete_VariableSet_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }

    private void incrementUnchecked() {
      drealJNI.VariableSet_Iterator_incrementUnchecked(swigCPtr, this);
    }

    private Variable derefUnchecked() {
      return new Variable(drealJNI.VariableSet_Iterator_derefUnchecked(swigCPtr, this), true);
    }

    private boolean isNot(VariableSet.Iterator other) {
      return drealJNI.VariableSet_Iterator_isNot(
          swigCPtr, this, VariableSet.Iterator.getCPtr(other), other);
    }
  }

  public VariableSet() {
    this(drealJNI.new_VariableSet__SWIG_0(), true);
  }

  public VariableSet(VariableSet other) {
    this(drealJNI.new_VariableSet__SWIG_1(VariableSet.getCPtr(other), other), true);
  }

  @Override
  public boolean isEmpty() {
    return drealJNI.VariableSet_isEmpty(swigCPtr, this);
  }

  @Override
  public void clear() {
    drealJNI.VariableSet_clear(swigCPtr, this);
  }

  private VariableSet.Iterator begin() {
    return new VariableSet.Iterator(drealJNI.VariableSet_begin(swigCPtr, this), true);
  }

  private VariableSet.Iterator end() {
    return new VariableSet.Iterator(drealJNI.VariableSet_end(swigCPtr, this), true);
  }

  public boolean addImpl(Variable key) {
    return drealJNI.VariableSet_addImpl(swigCPtr, this, Variable.getCPtr(key), key);
  }

  private boolean containsImpl(Variable key) {
    return drealJNI.VariableSet_containsImpl(swigCPtr, this, Variable.getCPtr(key), key);
  }

  private boolean removeImpl(Variable key) {
    return drealJNI.VariableSet_removeImpl(swigCPtr, this, Variable.getCPtr(key), key);
  }

  private int sizeImpl() {
    return drealJNI.VariableSet_sizeImpl(swigCPtr, this);
  }

  @SuppressWarnings("unused")
  private boolean hasNextImpl(VariableSet.Iterator itr) {
    return drealJNI.VariableSet_hasNextImpl(swigCPtr, this, VariableSet.Iterator.getCPtr(itr), itr);
  }
}
