/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sosy_lab.java_smt.solvers.bitwuzla.api;

public class BitwuzlaNative {
  public static String copyright() {
    return BitwuzlaNativeJNI.copyright();
  }

  public static String version() {
    return BitwuzlaNativeJNI.version();
  }

  public static String git_id() {
    return BitwuzlaNativeJNI.git_id();
  }

}
