#!/bin/sh

PRI=../../princess

TESTS="division.pri \
       division2.pri \
       inconsistent_basis.pri \
       ineqs_simplify0.pri \
       ineqs_simplify1.pri \
       ineqs_simplify2.pri \
       ineqs_simplify3.pri \
       ineqs_simplify4.pri \
       ineqs_simplify5.pri \
       inequations0.pri \
       inequations1.pri \
       inequations2.pri \
       inequations3.pri \
       nonLinInEqExample0.pri \
       nonLinInEqExample1.pri \
       nonLinInEqExample2.pri \
       nonLinInEqExample3.pri \
       nonLinInEqExample4.pri \
       quadraticInEq11.pri \
       quadraticInEq12.pri \
       quadraticInEq2.pri \
       quadraticInEq3.pri \
       quadraticInEq4.pri \
       quadraticInEq5.pri \
       quadraticInEq6.pri \
       quadraticInEq7.pri \
       quadraticInEq.pri \
       simplify0.pri \
       simplify10.pri \
       simplify11.pri \
       simplify12.pri \
       simplify13.pri \
       simplify15.pri \
       simplify16.pri \
       simplify17.pri \
       simplify18.pri \
       simplify19.pri \
       simplify1.pri \
       simplify20.pri \
       simplify21.pri \
       simplify22.pri \
       simplify23.pri \
       simplify24.pri \
       simplify25.pri \
       simplify27.pri \
       simplify2.pri \
       simplify3.pri \
       simplify4.pri \
       simplify5.pri \
       simplify6.pri \
       simplify7.pri \
       simplify8.pri \
       simplify9.pri \
       subsumptionExample.pri \
       simpleTermination.pri \
       aproveSMT809443464904014753.smt2 \
       bv-square.pri \
       bv-quadratic-eq.pri \
       mult-diff.pri \
       mult-model.pri \
       shift.pri \
       diffsquare.pri \
       mult-icp.pri \
       subsumptionBug.pri \
       polyReduceBug.pri \
       polyReduceBug2.smt2 \
       splittingBug2.pri \
       squares-div-2.pri"

# Tests currently not working:
#       linApprox.pri \
#       quadraticInEq10.pri \
#       quadraticInEq13.pri \
#       quadraticInEq14.pri \
#       quadraticInEq9.pri \

$PRI "$@" $TESTS 2>&1

$PRI "$@" -timeout=30000 splittingBug.pri 2>&1

TESTS="nonLinInEqExample2.pri \
       quadraticInEq5.pri"

$PRI "$@" +printProof $TESTS 2>&1
