/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sosy_lab.java_smt.solvers.leansmt;

public class LeanSMT implements LeanSMTConstants {
  public static int leansmt_wrapper_init() {
    return LeanSMTJNI.leansmt_wrapper_init();
  }

  public static int leansmt_wrapper_is_initialized() {
    return LeanSMTJNI.leansmt_wrapper_is_initialized();
  }

  public static void leansmt_wrapper_cleanup() {
    LeanSMTJNI.leansmt_wrapper_cleanup();
  }

  public static String leansmt_wrapper_get_error() {
    return LeanSMTJNI.leansmt_wrapper_get_error();
  }

  public static int leansmt_wrapper_set_path_prefix(String dir) {
    return LeanSMTJNI.leansmt_wrapper_set_path_prefix(dir);
  }

  public static java.math.BigInteger leansmt_wrapper_create_solver(int solver_kind) {
    return LeanSMTJNI.leansmt_wrapper_create_solver(solver_kind);
  }

  public static int leansmt_wrapper_delete_solver(java.math.BigInteger handle) {
    return LeanSMTJNI.leansmt_wrapper_delete_solver(handle);
  }

  public static int leansmt_wrapper_set_logic(java.math.BigInteger handle, String logic) {
    return LeanSMTJNI.leansmt_wrapper_set_logic(handle, logic);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_true() {
    return LeanSMTJNI.leansmt_wrapper_mk_true();
  }

  public static java.math.BigInteger leansmt_wrapper_mk_false() {
    return LeanSMTJNI.leansmt_wrapper_mk_false();
  }

  public static java.math.BigInteger leansmt_wrapper_mk_int_const(long value) {
    return LeanSMTJNI.leansmt_wrapper_mk_int_const(value);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_int_const_str(String value) {
    return LeanSMTJNI.leansmt_wrapper_mk_int_const_str(value);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_real_const(long num, long den) {
    return LeanSMTJNI.leansmt_wrapper_mk_real_const(num, den);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_real_const_str(String num, String den) {
    return LeanSMTJNI.leansmt_wrapper_mk_real_const_str(num, den);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_bv_const(long width, String value) {
    return LeanSMTJNI.leansmt_wrapper_mk_bv_const(width, value);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_app1(String op, java.math.BigInteger term) {
    return LeanSMTJNI.leansmt_wrapper_mk_app1(op, term);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_app2(String op, java.math.BigInteger lhs, java.math.BigInteger rhs) {
    return LeanSMTJNI.leansmt_wrapper_mk_app2(op, lhs, rhs);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_extract(java.math.BigInteger term, long msb, long lsb) {
    return LeanSMTJNI.leansmt_wrapper_mk_extract(term, msb, lsb);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_indexed_app1(String op, long index, java.math.BigInteger term) {
    return LeanSMTJNI.leansmt_wrapper_mk_indexed_app1(op, index, term);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_symbol(String symbol) {
    return LeanSMTJNI.leansmt_wrapper_mk_symbol(symbol);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_apply(
      java.math.BigInteger fn, java.math.BigInteger arg) {
    return LeanSMTJNI.leansmt_wrapper_mk_apply(fn, arg);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_not(java.math.BigInteger t) {
    return LeanSMTJNI.leansmt_wrapper_mk_not(t);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_and(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_and(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_or(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_or(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_xor(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_xor(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_implies(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_implies(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_iff(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_iff(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_ite(java.math.BigInteger cond, java.math.BigInteger then_branch, java.math.BigInteger else_branch) {
    return LeanSMTJNI.leansmt_wrapper_mk_ite(cond, then_branch, else_branch);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_eq(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_eq(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_distinct(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_distinct(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_lt(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_lt(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_le(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_le(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_gt(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_gt(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_ge(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_ge(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_add(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_add(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_sub(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_sub(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_mul(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_mul(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_div(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_div(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_mod(java.math.BigInteger t1, java.math.BigInteger t2) {
    return LeanSMTJNI.leansmt_wrapper_mk_mod(t1, t2);
  }

  public static java.math.BigInteger leansmt_wrapper_mk_neg(java.math.BigInteger t) {
    return LeanSMTJNI.leansmt_wrapper_mk_neg(t);
  }

  public static int leansmt_wrapper_assert(java.math.BigInteger solver, java.math.BigInteger term) {
    return LeanSMTJNI.leansmt_wrapper_assert(solver, term);
  }

  public static int leansmt_wrapper_declare_fun(
      java.math.BigInteger solver, String name, String argSorts, String returnSort) {
    return LeanSMTJNI.leansmt_wrapper_declare_fun(solver, name, argSorts, returnSort);
  }

  public static int leansmt_wrapper_check_sat(java.math.BigInteger solver) {
    return LeanSMTJNI.leansmt_wrapper_check_sat(solver);
  }

  public static String leansmt_wrapper_get_model(java.math.BigInteger solver) {
    return LeanSMTJNI.leansmt_wrapper_get_model(solver);
  }

  public static String leansmt_wrapper_get_value(java.math.BigInteger solver, java.math.BigInteger term) {
    return LeanSMTJNI.leansmt_wrapper_get_value(solver, term);
  }
}
