#!/bin/sh

# Tests that should not be provable

PRI=../../princess

TESTS="optimisation7.pri predicates3.pri \
       simpleEq7.pri simpleEq8.pri simpleEq10.pri \
       splitEqBug.pri splitEqBug2.pri \
       wrongEqualities0.pri wrongEqualities1.pri \
       wrongInequalities0.pri wrongInequalities1.pri \
       wrongInequalities2.pri wrongInequalities3.pri \
       wrongInequalities4.pri wrongInequalities5.pri \
       wrongInequalities6.pri wrongNameResolution.pri \
       reduceWithConjunctionBug.pri
       wrongFunctionAxioms.pri \
       relationalFun2.pri omegaBug.pri \
       uniExConstants1.pri uniExConstantsBug.pri \
       wrongModel.pri bool-fun-1.pri"

$PRI "$@" $TESTS

# Tests where we have to suppress parts of the output because it is
# too nondeterministic

TESTS="cryptarithm.pri cryptarithm4.pri"

$PRI "$@" $TESTS 2>&1 | grep -v "^D"

# Special settings for this testcase

$PRI "$@" -genTotalityAxioms +reverseFunctionalityPropagation -tightFunctionScopes ricart-agrawala7.smt2
