package org.sosy_lab.java_smt.solvers.bitwuzla;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

public final class BitwuzlaResult {

  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
  public static final BitwuzlaResult BITWUZLA_SAT =
      BitwuzlaResult.of("BITWUZLA_SAT", BitwuzlaJNI.BITWUZLA_SAT_get());
  public static final BitwuzlaResult BITWUZLA_UNSAT =
      BitwuzlaResult.of("BITWUZLA_UNSAT", BitwuzlaJNI.BITWUZLA_UNSAT_get());
  public static final BitwuzlaResult BITWUZLA_UNKNOWN =
      BitwuzlaResult.of("BITWUZLA_UNKNOWN", BitwuzlaJNI.BITWUZLA_UNKNOWN_get());

  private static BitwuzlaResult[] swigValues = {BITWUZLA_SAT, BITWUZLA_UNSAT, BITWUZLA_UNKNOWN};

  public int swigValue() {
    return swigValue;
  }

  @Override
  public String toString() {
    return swigName;
  }

  public static BitwuzlaResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length
        && swigValue >= 0
        && swigValues[swigValue].swigValue == swigValue) {return swigValues[swigValue];}
    for (int i = 0; i < swigValues.length; i++) {
      if (swigValues[i].swigValue == swigValue) {
        return swigValues[i];
      }
    }
    throw new IllegalArgumentException(
        "No enum " + BitwuzlaResult.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BitwuzlaResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BitwuzlaResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
  }

  private static BitwuzlaResult of(String swigName, int swigValue) {
    BitwuzlaResult res = new BitwuzlaResult(swigName, swigValue);
    BitwuzlaResult.swigNext = res.swigValue + 1;
    return res;
  }
}
