// This file is part of JavaSMT,
// an API wrapper for a collection of SMT solvers:
// https://github.com/sosy-lab/java-smt
//
// SPDX-FileCopyrightText: 2025 Dirk Beyer <https://www.sosy-lab.org>
//
// SPDX-License-Identifier: Apache-2.0

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sosy_lab.java_smt.solvers.opensmt.api;

public class VectorPTRef extends java.util.AbstractList<PTRef> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorPTRef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorPTRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VectorPTRef obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OsmtNativeJNI.delete_VectorPTRef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorPTRef(PTRef[] initialElements) {
    this();
    reserve(initialElements.length);

    for (PTRef element : initialElements) {
      add(element);
    }
  }

  public VectorPTRef(Iterable<PTRef> initialElements) {
    this();
    for (PTRef element : initialElements) {
      add(element);
    }
  }

  public PTRef get(int index) {
    return doGet(index);
  }

  public PTRef set(int index, PTRef e) {
    return doSet(index, e);
  }

  public boolean add(PTRef e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, PTRef e) {
    modCount++;
    doAdd(index, e);
  }

  public PTRef remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorPTRef() {
    this(OsmtNativeJNI.new_VectorPTRef__SWIG_0(), true);
  }

  public VectorPTRef(VectorPTRef other) {
    this(OsmtNativeJNI.new_VectorPTRef__SWIG_1(VectorPTRef.getCPtr(other), other), true);
  }

  public long capacity() {
    return OsmtNativeJNI.VectorPTRef_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    OsmtNativeJNI.VectorPTRef_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OsmtNativeJNI.VectorPTRef_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OsmtNativeJNI.VectorPTRef_clear(swigCPtr, this);
  }

  public VectorPTRef(int count, PTRef value) {
    this(OsmtNativeJNI.new_VectorPTRef__SWIG_2(count, PTRef.getCPtr(value), value), true);
  }

  private int doSize() {
    return OsmtNativeJNI.VectorPTRef_doSize(swigCPtr, this);
  }

  private void doAdd(PTRef x) {
    OsmtNativeJNI.VectorPTRef_doAdd__SWIG_0(swigCPtr, this, PTRef.getCPtr(x), x);
  }

  private void doAdd(int index, PTRef x) {
    OsmtNativeJNI.VectorPTRef_doAdd__SWIG_1(swigCPtr, this, index, PTRef.getCPtr(x), x);
  }

  private PTRef doRemove(int index) {
    return new PTRef(OsmtNativeJNI.VectorPTRef_doRemove(swigCPtr, this, index), true);
  }

  private PTRef doGet(int index) {
    return new PTRef(OsmtNativeJNI.VectorPTRef_doGet(swigCPtr, this, index), false);
  }

  private PTRef doSet(int index, PTRef val) {
    return new PTRef(OsmtNativeJNI.VectorPTRef_doSet(swigCPtr, this, index, PTRef.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    OsmtNativeJNI.VectorPTRef_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
